### ISSUE TITLE
The DLNA server is not discoverable on the network

### ISSUE THREAD

**Issue by Kobtul** [jpspringall/serviio#1]
I used docker-compose from your image, but I can not see DLNA server on any of my devices.
I am running docker on raspberry pi, Ubuntu server 21.10
Serviio is running and console is accessible.
Can you please point how to make the DLNA server discoverable?

**Comment by jpspringall** [comment]
Hi Kobtul,

The only time i have seen this issue is when the network is not configured in the docker-compose, it needs to be configured to use host network mode.

e.g:

services:
  serviio:
    container_name: serviio
    image: jpspringall/serviio
    network_mode: "host"

**Comment by Kobtul** [comment]
Thanks, in docker compose there are port definitions so I assumed that is not necessary. My bad :)

**Comment by jpspringall** [comment]
Been there, done the same thing :-)
